[package]
name = "emctl-core"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { workspace = true }
rand = "0.9.2"
serde_yaml = "0.9.34"
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio"] }
